"""add_recipe_ingredients_to_menu_items

Revision ID: e596aba7f1f8
Revises: 952dd987a2f3
Create Date: 2026-05-20 02:39:19.895032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e596aba7f1f8'
down_revision: Union[str, None] = '952dd987a2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('recipe_ingredients', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'recipe_ingredients')
    # ### end Alembic commands ###
